# Example for parameters to excecute

# I/O
io_parameters:
  data_tiled_uri: "http://data/tiled/uri"
  data_tiled_api_key: a1b2c3
  mask_tiled_uri: "http://mask/tiled/uri"
  mask_tiled_api_key: d4e5f6
  seg_tiled_uri: "http://seg/tiled/uri"
  uid_save: pytest1
  uid_retrieve: pytest1
  models_dir: .

model_parameters:
  network: "DLSIA TUNet"
  num_classes: 3
  num_epochs: 3
  optimizer: "Adam"
  criterion: "CrossEntropyLoss"
  weights: "[1.0, 2.0, 0.5]"
  learning_rate: 0.1
  activation: "ReLU"
  normalization: "BatchNorm2d"
  convolution: "Conv2d"

  qlty_window: 2
  qlty_step: 1
  qlty_border: 1

  shuffle_train: True
  batch_size_train: 1

  batch_size_val: 1

  batch_size_inference: 2
  val_pct: 0.2

  depth: 4
  base_channels: 8
  growth_rate: 2
  hidden_rate: 1
